window.___jsl=window.___jsl||{};
window.___jsl.h=window.___jsl.h||'m;\/_\/apps-static\/_\/js\/widget\/__features__\/rt=j\/ver=jrEAesdR5QE.en_GB.\/sv=1\/am=!74w1rtNiplGIAAr7Ig\/d=1\/';
window.___jsl.l=[];
window.___gpq=[];
window.gapi=window.gapi||{};
window.gapi.plusone=window.gapi.plusone||(function(){
  function f(n){return function(){window.___gpq.push(n,arguments)}}
  return{go:f('go'),render:f('render')}})();
function __bsld(){var p=window.gapi.plusone=window.googleapisv0.plusone;var f;while(f=window.___gpq.shift()){
  p[f]&&p[f].apply(p,window.___gpq.shift())}
p=window.gapi.plus=window.googleapisv0.plus;while(f=window.___gbq.shift()){
  p[f]&&p[f].apply(p,window.___gbq.shift())}
if (gadgets.config.get("gwidget")["parsetags"]!=="explicit"){gapi.plusone.go();}}
window.___gbq=[];
window.gapi.plus=window.gapi.plus||(function(){
  function f(n){return function(){window.___gbq.push(n,arguments)}}
  return{go:f('go'),render:f('render')}})();
window.__GOOGLEAPIS=window.__GOOGLEAPIS||{};
window.__GOOGLEAPIS.iframes=window.__GOOGLEAPIS.iframes||{};
window.__GOOGLEAPIS.iframes.plus=window.__GOOGLEAPIS.iframes.plus||{url:':socialhost:/u/:session_index:/_/pages/badge'};window['___jsl'] = window['___jsl'] || {};window['___jsl']['uc'] = 'https:\/\/apis.google.com\/js\/plusone.js';window['___jsl']['u'] = 'https:\/\/apis.google.com\/js\/plusone.js';window['___jsl']['f'] = ['googleapis.client','plusone','gcm_ppb'];window['___jsl']['ms'] = 'https://plus.google.com';(window['___jsl']['ci'] = (window['___jsl']['ci'] || [])).push({"gwidget":{"parsetags":"onload"},"iframes":{"sharebox":{"params":{"json":"&"},"url":":socialhost:/:session_prefix:_/sharebox/dialog"},"plus":{"url":":socialhost:/:session_prefix:_/pages/badge"},":socialhost:":"https://plusone.google.com","plusone_m":{"url":":socialhost:/:session_prefix:_/+1/fastbutton","params":{"count":"","size":"","url":""}},"card":{"params":{"style":"#","userid":"&"},"url":":socialhost:/u/:session_index:/_/hovercard/card"},"plusone":{"url":":socialhost:/:session_prefix:_/+1/fastbutton","params":{"count":"","size":"","url":""}}},"googleapis.config":{"requestCache":{"enabled":true},"methods":{"chili.people.list":true,"pos.plusones.list":true,"pos.plusones.get":true,"chili.people.get":true,"pos.plusones.insert":true,"chili.activities.list":true,"pos.plusones.delete":true,"chili.activities.get":true,"chili.activities.search":true,"pos.plusones.getSignupState":true},"versions":{"chili":"v1","pos":"v1"},"rpc":"/rpc","transport":{"isProxyShared":true},"sessionCache":{"enabled":true},"root-1p":"https://clients6.google.com","root":"https://www.googleapis.com","xd3":"/static/proxy.html","developerKey":"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ","auth":{"useInterimAuth":false}}});var gapi=window.gapi||{};gapi.client=window.gapi&&window.gapi.client||{};
window.gapi=window.gapi||{};
(function(){var z=void 0,A=void 0,B="___jsl",U="h",C="l",V="m",D="ms",p="cu",W="c",X="cm",Y="o",o="p",m="q",E="lc",F="Q",t="I",u="_",v="https://ssl.gstatic.com",Z="/webclient/js",$="/webclient/jsx/",G="https://apis.google.com",H=".js",aa="gcjs-3p",ba=/^(https?:)?\/\/([^/:@]*)(:[0-9]+)?(\/[\w.,:!=/-]*)(\?[^#]*)?(#.*)?$/,I=/^[?#]([^&]*&)*jsh=([^&]*)/,J="d",q="r",ca="f",r="m",K="n",da="sync",ea="callback",w="config",L="nodep",M="gapi.load: ",N=function(a,b){z&&z(a,b);throw M+a+(b&&" "+b);},O=function(a){A&&
A(a);var b=window.console;b&&b.warn(M+a)},fa=function(a,b,c){a=a[U];if(b=b&&I.exec(b)||c&&I.exec(c))try{a=decodeURIComponent(b[2])}catch(d){O("Invalid hint "+b[2])}return a},P=function(a){a.sort();for(var b=0;b<a.length;)!a[b]||b&&a[b]==a[b-1]?a.splice(b,1):++b},Q=function(a,b){for(var c=!0,d=0,f=0,e,g;c&&(e=a[d])&&(g=b[f]);)e==g?++d:e<g&&(c=!1),++f;return c&&!e},ga=function(a){if("loading"!=document.readyState)return!1;if("undefined"!=typeof window.___gapisync)return window.___gapisync;if(a&&(a=
a[da],"undefined"!=typeof a))return a;for(var a=document.getElementsByTagName("meta"),b=0,c;c=a[b];++b)if("generator"==c.getAttribute("name")&&"blogger"==c.getAttribute("content"))return!0;return!1},R=function(a,b){if(ga(a))document.write('<script src="'+encodeURI(b)+'"><\/script>');else{var c=b,d=document.createElement("script");d.setAttribute("src",c);d.async=!0;c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(d,c)}},S=function(a,b,c,d,f,e){var g=c.shift(),h;h=g==q?v:g==r?
d[D]||G:(h=c.shift())&&h.replace(/\/+$/,"");var j;g==q?(j=c.shift(),j=(j.indexOf($)?Z+"/":"")+j):j=c.shift();var i=g==J,k=i&&c.shift()||aa,c=i&&c.shift();if(g==J)e=b,b=j,f=k,a="/"+a.join(":")+(e.length?"!"+e.join(":"):"")+H+"?container="+f+"&c=2&jsload=0",b&&(a+="&r="+b),"d"==c&&(a+="&debug=1");else if(g==q||g==ca)e=b,b=j,a=(b.indexOf("/")?"/":"")+b+"/"+a.join("__")+(e.length?"--"+e.join("__"):"")+H;else if(g==r||g==K)b=j,a=a.join(",").replace(/\./g,"_").replace(/-/g,"_"),a=b.replace("__features__",
a),a=f[L]?a.replace("/d=1/","/d=0/"):a,e&&(a.match(/\/$/)||(a+="/"),a+="cb=gapi."+encodeURIComponent(e));else return O("Unknown hint type "+g),"";if(!h)return"";h+=a;a=h;e=d;if(b=d=ba.exec(a))if(b=!/\.\.|\/\//.test(d[4]))b:if(b=a,d=d[2],g==q)b=b.substr(0,v.length)==v;else if(g==r)d=e[D]||G,b=b.substr(0,d.length)==d;else{g=e[V];if(d&&g){g=g.split(",");e=0;for(b=g.length;e<b;++e)if(f=g[e],c=d.lastIndexOf(f),(0==c||"."==f.charAt(0)||"."==d.charAt(c-1))&&d.length-f.length==c){b=!0;break b}}b=!1}b||N("Invalid URI",
a);return h},ha=function(a,b,c){(a[m]=a[m]||[]).push([b,c])},x=function(a){a[m]&&0<a[m].length&&(window.gapi.load||T).apply(null,a[m].shift())},s=function(a){if(a)try{a()}catch(b){return b}return null},n=window.gapi,ia=function(){if(n[u])return n[u];var a;if((a=Object.create)&&/\[native code\]/.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return n[u]=a},ja=function(a,b,c,d,f){var e=f[F]=f[F]||[],g=f[E]=f[E]||{};e.push([a,b,d]);n[c]=function(b){n[c]=void 0;if(!g[a]){g[a]=b;for(var b=e,d=
g,i=f,k;b[0]&&d[b[0][0]];){var l=b.shift(),y=l[2],m=i;y&&(n.config?n.config.update(y):(m[p]=m[p]||[]).push(y));d[l[0]].call(window,ia());d[l[0]]=!0;(l=s(l[1]))&&!k&&(k=l)}i[o]=void 0;x(i);if(k)throw k;}}},ka=function(a){a[t]||(a[t]=0);return"loaded"+a[t]++},T=function(a,b){var c,d={};"function"!==typeof b?(d=b||{},c=d[ea]):c=b;var f=window[B]=window[B]||{},e=fa(f,window.location.search,window.location.hash),g=e&&!!e.match(/\/gapi\/|ms=gapi/);if(f[o])ha(f,a,b);else{e||N("No hint present","");var h=
e.split(";"),j=h[0]==r||h[0]==K,e=a.split(":");d[L]||P(e);var i=f[C]=f[C]||[];P(i);if(g){if(!Q(e,i)&&(g=ka(f),h=S(e,i,h,f,d,g))){f[o]=e;ja(h,c,g,d[w],f);i.push.apply(i,e);R(d,h);return}if(c)var k=s(c)}else{if(!Q(e,i)){var l=j?X:W,h=S(e,i,h,f,d,null);d[w]&&(f[p]=f[p]||[]).push(d[w]);if(h){f[o]=e;f[Y]=1;f[l]=function(){f[o]=void 0;f[l]=void 0;var a=s(c);x(f);if(a)throw a;};i.push.apply(i,e);R(d,h);return}}k=s(c)}x(f);if(k)throw k;}};gapi.loader={load:T}})();
gapi.load=window.___jsl&&window.___jsl.il&&window.gapi&&window.gapi.load||gapi.loader.load;
(window.gapi=window.gapi||{}).load=window.___jsl&&window.___jsl.il&&window.gapi.load||gapi.load;
gapi.load('googleapis.client:plusone:gcm_ppb', {'callback': window['__bsld']  });